server:
  port: 8080
  servlet: #2.X version spring boot style:server.servlet.context-path: /api
   context-path: /api

spring:
  datasource:
    url: jdbc:sqlserver://127.0.0.1:1433;database=elemalldb;integratedSecurity=false
    username: sa
    password: xbg123!@#
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

mybatis:
  mapper-locations: classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.store.clientsoft.*.entity

#showSql
logging: 
  config: classpath:logback-spring.xml
  level: 
    com.store.clientsoft.*.dao: info