server:
  port: 8080
  servlet: #2.X version spring boot style:server.servlet.context-path: /api
   context-path: /api

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/elemalldb_dit?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*/*Mapper.xml
  type-aliases-package: com.annguo.clientsoft.*.entity

#showSql
logging:
  level:
    com:
      annguo:
        mapper : debug